Tried to get the generic trait bounds setup correctly so that generic container objects can be converted to Widget objects in widget adapter objects. This lead to getting an “error[E0277]: the trait bound `gtk_estate::gtk4::Widget: IsA<gtk_estate::libadwaita::ApplicationWindow>` is not satisfied” error in simple_unix_time_outputer so I’ll have to figure out another solution.
WIP